/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestsonlyRouteRouteImport } from './routes/_guestsonly/route'
import { Route as AdminonlyRouteRouteImport } from './routes/_adminonly/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestsonlyLoginRouteImport } from './routes/_guestsonly/login'
import { Route as AdminonlyEditorRouteImport } from './routes/_adminonly/editor'

const GuestsonlyRouteRoute = GuestsonlyRouteRouteImport.update({
  id: '/_guestsonly',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminonlyRouteRoute = AdminonlyRouteRouteImport.update({
  id: '/_adminonly',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsonlyLoginRoute = GuestsonlyLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestsonlyRouteRoute,
} as any)
const AdminonlyEditorRoute = AdminonlyEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AdminonlyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof AdminonlyEditorRoute
  '/login': typeof GuestsonlyLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof AdminonlyEditorRoute
  '/login': typeof GuestsonlyLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_adminonly': typeof AdminonlyRouteRouteWithChildren
  '/_guestsonly': typeof GuestsonlyRouteRouteWithChildren
  '/_adminonly/editor': typeof AdminonlyEditorRoute
  '/_guestsonly/login': typeof GuestsonlyLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/login'
  id:
    | '__root__'
    | '/'
    | '/_adminonly'
    | '/_guestsonly'
    | '/_adminonly/editor'
    | '/_guestsonly/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminonlyRouteRoute: typeof AdminonlyRouteRouteWithChildren
  GuestsonlyRouteRoute: typeof GuestsonlyRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guestsonly': {
      id: '/_guestsonly'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestsonlyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminonly': {
      id: '/_adminonly'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminonlyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guestsonly/login': {
      id: '/_guestsonly/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestsonlyLoginRouteImport
      parentRoute: typeof GuestsonlyRouteRoute
    }
    '/_adminonly/editor': {
      id: '/_adminonly/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AdminonlyEditorRouteImport
      parentRoute: typeof AdminonlyRouteRoute
    }
  }
}

interface AdminonlyRouteRouteChildren {
  AdminonlyEditorRoute: typeof AdminonlyEditorRoute
}

const AdminonlyRouteRouteChildren: AdminonlyRouteRouteChildren = {
  AdminonlyEditorRoute: AdminonlyEditorRoute,
}

const AdminonlyRouteRouteWithChildren = AdminonlyRouteRoute._addFileChildren(
  AdminonlyRouteRouteChildren,
)

interface GuestsonlyRouteRouteChildren {
  GuestsonlyLoginRoute: typeof GuestsonlyLoginRoute
}

const GuestsonlyRouteRouteChildren: GuestsonlyRouteRouteChildren = {
  GuestsonlyLoginRoute: GuestsonlyLoginRoute,
}

const GuestsonlyRouteRouteWithChildren = GuestsonlyRouteRoute._addFileChildren(
  GuestsonlyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminonlyRouteRoute: AdminonlyRouteRouteWithChildren,
  GuestsonlyRouteRoute: GuestsonlyRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
