/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoauthRouteRouteImport } from './routes/_noauth/route'
import { Route as AdminonlyRouteRouteImport } from './routes/_adminonly/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoauthLoginRouteImport } from './routes/_noauth/login'
import { Route as AdminonlyEditorRouteImport } from './routes/_adminonly/editor'

const NoauthRouteRoute = NoauthRouteRouteImport.update({
  id: '/_noauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminonlyRouteRoute = AdminonlyRouteRouteImport.update({
  id: '/_adminonly',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoauthLoginRoute = NoauthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => NoauthRouteRoute,
} as any)
const AdminonlyEditorRoute = AdminonlyEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AdminonlyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof AdminonlyEditorRoute
  '/login': typeof NoauthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof AdminonlyEditorRoute
  '/login': typeof NoauthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_adminonly': typeof AdminonlyRouteRouteWithChildren
  '/_noauth': typeof NoauthRouteRouteWithChildren
  '/_adminonly/editor': typeof AdminonlyEditorRoute
  '/_noauth/login': typeof NoauthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/login'
  id:
    | '__root__'
    | '/'
    | '/_adminonly'
    | '/_noauth'
    | '/_adminonly/editor'
    | '/_noauth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminonlyRouteRoute: typeof AdminonlyRouteRouteWithChildren
  NoauthRouteRoute: typeof NoauthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_noauth': {
      id: '/_noauth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NoauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminonly': {
      id: '/_adminonly'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminonlyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_noauth/login': {
      id: '/_noauth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof NoauthLoginRouteImport
      parentRoute: typeof NoauthRouteRoute
    }
    '/_adminonly/editor': {
      id: '/_adminonly/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AdminonlyEditorRouteImport
      parentRoute: typeof AdminonlyRouteRoute
    }
  }
}

interface AdminonlyRouteRouteChildren {
  AdminonlyEditorRoute: typeof AdminonlyEditorRoute
}

const AdminonlyRouteRouteChildren: AdminonlyRouteRouteChildren = {
  AdminonlyEditorRoute: AdminonlyEditorRoute,
}

const AdminonlyRouteRouteWithChildren = AdminonlyRouteRoute._addFileChildren(
  AdminonlyRouteRouteChildren,
)

interface NoauthRouteRouteChildren {
  NoauthLoginRoute: typeof NoauthLoginRoute
}

const NoauthRouteRouteChildren: NoauthRouteRouteChildren = {
  NoauthLoginRoute: NoauthLoginRoute,
}

const NoauthRouteRouteWithChildren = NoauthRouteRoute._addFileChildren(
  NoauthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminonlyRouteRoute: AdminonlyRouteRouteWithChildren,
  NoauthRouteRoute: NoauthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
