packages:
  - apps/*
  - configs/*
  - designs/*
  - packages/*

catalog:
  '@justkits/svg2tsx': ^1.0.3
  '@testing-library/react': ^16.3.2
  '@types/node': ^25.0.10
  '@types/react': ^19.2.9
  '@vanilla-extract/css': ^1.18.0
  '@vitest/coverage-v8': 4.0.18
  eslint: ^9.39.2
  jsdom: ^27.4.0
  react: ^19.2.3
  react-dom: ^19.2.3
  rimraf: ^6.1.2
  typescript: ^5.9.3
  vitest: ^4.0.18

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
