packages:
  - apps/*
  - configs/*
  - packages/*

catalog:
  '@justkits/svg2tsx': ^1.1.1
  '@testing-library/react': ^16.3.2
  '@types/node': ^25.3.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vanilla-extract/css': ^1.18.0
  '@vanilla-extract/dynamic': ^2.1.5
  '@vanilla-extract/recipes': ^0.5.7
  '@vanilla-extract/vite-plugin': ^5.1.4
  '@vitest/coverage-v8': 4.0.18
  clsx: ^2.1.1
  eslint: ^9.39.2
  jsdom: ^28.1.0
  react: ^19.2.4
  react-dom: ^19.2.4
  rimraf: ^6.1.3
  typescript: ^5.9.3
  vitest: ^4.0.18
  zod: ^4.3.6

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
