packages:
  - apps/*
  - configs/*
  - designs/*
  - packages/*

catalog:
  '@testing-library/react': ^16.3.2
  '@types/react': ^19.2.8
  '@vitest/coverage-v8': 4.0.17
  eslint: ^9.39.2
  jsdom: ^27.4.0
  rimraf: ^6.1.2
  vitest: ^4.0.17

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
