# Generated by Django 6.0.1 on 2026-02-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(max_length=20)),
                ('section', models.IntegerField(choices=[(1, 'Devlog'), (2, 'Lounge')])),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': '게시글 유형',
                'verbose_name_plural': '게시글 유형',
                'db_table': 'post_types',
            },
        ),
    ]
