# Generated by Django 6.0.1 on 2026-02-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('posttypes', '0001_initial'),
        ('series', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('thumbnail_url', models.URLField()),
                ('is_published', models.BooleanField(default=False)),
                ('extras', models.JSONField(default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='categories.category')),
                ('post_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='posttypes.posttype')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='series.series')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='tags.tag')),
            ],
            options={
                'verbose_name': '포스트',
                'verbose_name_plural': '포스트',
                'db_table': 'posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='posts_slug_6da55a_idx'), models.Index(fields=['-created_at'], name='posts_created_2e2442_idx')],
            },
        ),
    ]
