# Generated by Django 6.0.1 on 2026-02-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('section', models.IntegerField(choices=[(1, 'Devlog'), (2, 'AFK')])),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'db_table': 'categories',
            },
        ),
    ]
