# Generated by Django 5.2.5 on 2025-08-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '게시글 유형',
                'verbose_name_plural': '게시글 유형',
                'db_table': 'post_type',
                'ordering': ['order', 'id'],
            },
        ),
    ]
