# Generated by Django 5.2.4 on 2025-08-11 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('kor_name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True)),
                ('icon', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 그룹',
                'db_table': 'category_group',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('kor_name', models.CharField(blank=True, max_length=80)),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True)),
                ('icon', models.CharField(max_length=80)),
                ('cover_image', models.URLField()),
                ('image_credit_html', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='devlog.categorygroup')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'db_table': 'category',
                'ordering': ['group__order', 'order', 'id'],
            },
        ),
    ]
